### ISSUE TITLE
MUX Stat Config is freezing player's UI

### ISSUE THREAD

**Issue by Grandpasoul** [muxinc/mux-stats-sdk-bitmovin-android#8] opened 2022-09-20 14:36 UTC
Hi, we are having some issues on several users since Sep 16th

Bitmovin Version: 3.23.0 (we tested with these 3 version, 3.11.1 and 3.18.1, no problems were found, we published the app 2 days before the issue appeared)
MUX SDK Version: 0.5.1

What is happening: Mux configuration is freezing the player UI, content audio can be listened, after a while Android alert pop up.

Here is the Stat Configuration:

```
val player = Player.create(this, playerConfig = playerConfig).also {
                bView.bitmovinPlayerView.player = it
            }
            //setup player listeners
            setupPlayerListeners()
            //Load playlist
            player.load(playlistConfig)
            setMUXConfig()
```

```
private fun setMUXConfig() {
        Log.e("here", "MUX Config")

        try {
            val customerPlayerData = CustomerPlayerData()
            customerPlayerData.environmentKey = BuildConfig.MUX_KEY
            val customerVideoData = CustomerVideoData()
            customerVideoData.videoTitle = titleVideo
            customerVideoData.videoId = titleVideoID
            customerVideoData.videoSeries = episodeName
            customerPlayerData.playerInitTime = getCurrentNowMilliseconds()
            customerPlayerData.subPropertyId = BuildConfig.SUB_PROPERTY_ID
            val customerData = CustomerData(customerPlayerData, customerVideoData, null)

            muxStatsBitmovin = MuxStatsSDKBitmovinPlayer(
                this,
                bView.bitmovinPlayerView,
                "Riivi",
                customerData)

            val size = Point()
            windowManager.defaultDisplay.getSize(size)
            muxStatsBitmovin?.setScreenSize(size.x, size.y)

        } catch (e: Exception){
            Log.e("mux", "${e.message}")
        }

    }
```

And here is the Stacktrace:

```
  at com.mux.stats.sdk.muxstats.MuxStats.handle (unavailable:2)
  at com.mux.stats.sdk.core.events.EventBus.dispatch (unavailable:24)
  at com.mux.stats.sdk.muxstats.bitmovinplayer.MuxStatsSDKBitmovinPlayer.dispatch (MuxStatsSDKBitmovinPlayer.java:587)
  at com.mux.stats.sdk.muxstats.bitmovinplayer.MuxStatsSDKBitmovinPlayer.buffering (MuxStatsSDKBitmovinPlayer.java:386)
  at com.mux.stats.sdk.muxstats.bitmovinplayer.MuxStatsSDKBitmovinPlayer.lambda$new$10$com-mux-stats-sdk-muxstats-bitmovinplayer-MuxStatsSDKBitmovinPlayer (MuxStatsSDKBitmovinPlayer.java:263)
  at com.mux.stats.sdk.muxstats.bitmovinplayer.MuxStatsSDKBitmovinPlayer$$ExternalSyntheticLambda11.onEvent (unavailable:4)
  at com.bitmovin.player.api.event.EventEmitter$DefaultImpls$d.a (SourceFile:1)
  at com.bitmovin.player.api.event.EventEmitter$DefaultImpls$d.invoke (SourceFile:1)
  at com.bitmovin.player.u.b.b (SourceFile:206)
  at com.bitmovin.player.u.d.a (SourceFile:1)
  at com.bitmovin.player.f.p0.a (SourceFile:42)
  at com.bitmovin.player.f.p0.a (SourceFile:1)
  at com.bitmovin.player.f.p0.b (SourceFile:1)
  at com.bitmovin.player.f.p0$a.a (SourceFile:2)
  at com.bitmovin.player.f.p0$a.invoke (SourceFile:1)
  at kotlinx.coroutines.flow.FlowKt__TransformKt$onEach$$inlined$unsafeTransform$1$2.emit (Emitters.kt:223)
  at kotlinx.coroutines.flow.StateFlowImpl.collect (StateFlow.kt:398)
  at kotlinx.coroutines.flow.FlowKt__TransformKt$onEach$$inlined$unsafeTransform$1.collect (SafeCollector.common.kt:113)
  at kotlinx.coroutines.flow.FlowKt__CollectKt.collect (Collect.kt:30)
  at kotlinx.coroutines.flow.FlowKt.collect (unavailable:1)
  at kotlinx.coroutines.flow.FlowKt__CollectKt$launchIn$1.invokeSuspend (Collect.kt:50)
  at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith (ContinuationImpl.kt:33)
  at kotlinx.coroutines.DispatchedTask.run (DispatchedTask.kt:106)
  at android.os.Handler.handleCallback (Handler.java:938)
  at android.os.Handler.dispatchMessage (Handler.java:99)
  at android.os.Looper.loopOnce (Looper.java:226)
  at android.os.Looper.loop (Looper.java:313)
  at android.app.ActivityThread.main (ActivityThread.java:8663)
  at java.lang.reflect.Method.invoke (Native method)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:571)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1135)
```

**Comment by daytime-em** [comment] 2022-09-21 16:23
Hello @Grandpasoul, thank you for reporting this issue. We are investigating now.

If it's possible, would you be able to supply the type of `Exception` being thrown (like, just above the stack trace)? Thank you!

**Comment by Grandpasoul** [comment] 2022-09-21 16:47
Hello @daytime-em thanks for the response.

The logs are from Google Play Console, we don't recognize any Exception on the stacktrace, actually that's all that the console catches, but the title says:

We are trying to replicate the issue to get more logs, but nothing for now.

```
unavailable - com.mux.stats.sdk.muxstats.MuxStats.handle
Input dispatching timed out
Thread: "main" tid=1 Blocked
```

```
  at com.mux.stats.sdk.muxstats.MuxStats.handle (unavailable)
  at com.mux.stats.sdk.core.events.EventBus.dispatch (unavailable)
  at com.mux.stats.sdk.muxstats.bitmovinplayer.MuxStatsSDKBitmovinPlayer.dispatch (MuxStatsSDKBitmovinPlayer.java:587)
  at com.mux.stats.sdk.muxstats.bitmovinplayer.MuxStatsSDKBitmovinPlayer.buffering (MuxStatsSDKBitmovinPlayer.java:386)
  at com.mux.stats.sdk.muxstats.bitmovinplayer.MuxStatsSDKBitmovinPlayer.lambda$new$10$com-mux-stats-sdk-muxstats-bitmovinplayer-MuxStatsSDKBitmovinPlayer (MuxStatsSDKBitmovinPlayer.java:263)
  at com.mux.stats.sdk.muxstats.bitmovinplayer.MuxStatsSDKBitmovinPlayer$$ExternalSyntheticLambda11.onEvent (D8$$SyntheticClass)
  at com.bitmovin.player.api.event.EventEmitter$DefaultImpls$d.a (SourceFile:1)
  at com.bitmovin.player.api.event.EventEmitter$DefaultImpls$d.invoke (SourceFile:1)
  at com.bitmovin.player.u.b.b (SourceFile:206)
  at com.bitmovin.player.u.d.a (SourceFile:1)
  at com.bitmovin.player.f.p0.a (SourceFile:42)
  at com.bitmovin.player.f.p0.a (SourceFile:1)
  at com.bitmovin.player.f.p0.b (SourceFile:1)
  at com.bitmovin.player.f.p0$a.a (SourceFile:2)
  at com.bitmovin.player.f.p0$a.invoke (SourceFile:1)
  at kotlinx.coroutines.flow.FlowKt__TransformKt$onEach$$inlined$unsafeTransform$1$2.emit (Emitters.kt:223)
  at kotlinx.coroutines.flow.StateFlowImpl.collect (StateFlow.kt:398)
  at kotlinx.coroutines.flow.FlowKt__TransformKt$onEach$$inlined$unsafeTransform$1.collect (SafeCollector.common.kt:113)
  at kotlinx.coroutines.flow.FlowKt__CollectKt.collect (Collect.kt:30)
  at kotlinx.coroutines.flow.FlowKt.collect (unavailable:1)
  at kotlinx.coroutines.flow.FlowKt__CollectKt$launchIn$1.invokeSuspend (Collect.kt:50)
  at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith (ContinuationImpl.kt:33)
  at kotlinx.coroutines.DispatchedTask.run (DispatchedTask.kt:106)
  at android.os.Handler.handleCallback (Handler.java:938)
  at android.os.Handler.dispatchMessage (Handler.java:99)
  at android.os.Looper.loop (Looper.java:236)
  at android.app.ActivityThread.main (ActivityThread.java:8107)
  at java.lang.reflect.Method.invoke (Native method)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:656)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:967)
```

This is the start of the Stacktrace

<img width="1118" alt="Captura de Pantalla 2022-09-21 a la(s) 13 45 43" src="https://user-images.githubusercontent.com/81314185/191563541-c3a740f9-c806-4019-ab17-9e503e5140eb.png">

**Comment by daytime-em** [comment] 2022-09-21 23:21
This issue has been isolated and a fix has been proposed here: https://github.com/muxinc/mux-stats-sdk-bitmovin-android/pull/9 We expect to release a fix soon.

**Comment by daytime-em** [comment] 2022-09-22 20:10
@Grandpasoul A fix should now be available in version in SDK version `0.5.2`, which is available on our mvn no. Thank you for your help with this issue!

**Comment by Grandpasoul** [comment] 2022-09-23 12:26
As a recommendation, update the docs @ https://docs.mux.com/guides/data/monitor-bitmovin-android#1-install-the-mux-data-sdk

Thank you very much.

**Comment by Grandpasoul** [comment] 2022-09-26 12:28
The issue re appreared but in less users.

We updated the MUX SDK to 0.5.2 and our app at Google Play Store, from a pool of 35k users, more than 1k active users the last weekend, 2 users still get this ANR. The last issue was 16 hrs ago.

<img width="1089" alt="Captura de Pantalla 2022-09-26 a la(s) 09 27 28" src="https://user-images.githubusercontent.com/81314185/192276046-cad05662-c2ed-4a6f-a7ff-a2e3eab4d664.png">

I think is the same stacktrace.

```
  at com.mux.stats.sdk.muxstats.MuxStats.handle (unavailable:2)
  at com.mux.stats.sdk.core.events.EventBus.dispatch (unavailable:24)
  at com.mux.stats.sdk.muxstats.bitmovinplayer.MuxStatsSDKBitmovinPlayer.dispatch (MuxStatsSDKBitmovinPlayer.java:587)
  at com.mux.stats.sdk.muxstats.bitmovinplayer.MuxStatsSDKBitmovinPlayer.buffering (MuxStatsSDKBitmovinPlayer.java:386)
  at com.mux.stats.sdk.muxstats.bitmovinplayer.MuxStatsSDKBitmovinPlayer.lambda$new$10$com-mux-stats-sdk-muxstats-bitmovinplayer-MuxStatsSDKBitmovinPlayer (MuxStatsSDKBitmovinPlayer.java:263)
  at com.mux.stats.sdk.muxstats.bitmovinplayer.MuxStatsSDKBitmovinPlayer$$ExternalSyntheticLambda11.onEvent (unavailable:4)
  at com.bitmovin.player.api.event.EventEmitter$DefaultImpls$d.a (SourceFile:1)
  at com.bitmovin.player.api.event.EventEmitter$DefaultImpls$d.invoke (SourceFile:1)
  at com.bitmovin.player.u.b.b (SourceFile:206)
  at com.bitmovin.player.u.d.a (SourceFile:1)
  at com.bitmovin.player.f.p0.a (SourceFile:42)
  at com.bitmovin.player.f.p0.a (SourceFile:1)
  at com.bitmovin.player.f.p0.b (SourceFile:1)
  at com.bitmovin.player.f.p0$a.a (SourceFile:2)
  at com.bitmovin.player.f.p0$a.invoke (SourceFile:1)
  at kotlinx.coroutines.flow.FlowKt__TransformKt$onEach$$inlined$unsafeTransform$1$2.emit (Emitters.kt:223)
  at kotlinx.coroutines.flow.StateFlowImpl.collect (StateFlow.kt:398)
  at kotlinx.coroutines.flow.FlowKt__TransformKt$onEach$$inlined$unsafeTransform$1.collect (SafeCollector.common.kt:113)
  at kotlinx.coroutines.flow.FlowKt__CollectKt.collect (Collect.kt:30)
  at kotlinx.coroutines.flow.FlowKt.collect (unavailable:1)
  at kotlinx.coroutines.flow.FlowKt__CollectKt$launchIn$1.invokeSuspend (Collect.kt:50)
  at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith (ContinuationImpl.kt:33)
  at kotlinx.coroutines.DispatchedTask.run (DispatchedTask.kt:106)
  at android.os.Handler.handleCallback (Handler.java:938)
  at android.os.Handler.dispatchMessage (Handler.java:99)
  at android.os.Looper.loopOnce (Looper.java:226)
  at android.os.Looper.loop (Looper.java:313)
  at android.app.ActivityThread.main (ActivityThread.java:8663)
  at java.lang.reflect.Method.invoke (Native method)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:567)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1135)
```

**Comment by daytime-em** [comment] 2022-09-26 17:13
@Grandpasoul Sorry this issue has not been fully resolved. It appears that bitmovin player can occasionally stall during all state queries, but there was one that we didn't see problems with in testing. I'll reopen this and eliminate the stall completely

**Comment by daytime-em** [comment] 2022-09-27 16:30
@Grandpasoul We are having some trouble reproducing this issue internally. If you don't mind, are the rest of the process threads in the crash report? This issue is due to another thread holding a lock required by the main thread, and we should be able to find out what is blocking that way.

Thank you for your help debugging this issue!

**Closed** 2022-11-18 23:24 UTC

**Comment by daytime-em** [comment] 2022-11-18 23:25
Hi @Grandpasoul 

v0.5.3 of the Bitmovin SDK is now deploying, containing a fix for this issue. I'm very sorry for the long turnaround on this. Thank you for your report!

**Comment by Grandpasoul** [comment] 2022-11-23 14:50
Hi @daytime-em 

Don't worry, we updated our app with some try/catches for safe mode. We will update on these days to review. I will let you know if some issue appears again. Thank you very much.

**Comment by Grandpasoul** [comment] 2022-12-16 14:05
Hi, after a few weeks we are going to publish our app with Mux Android SDK 0.5.3, no issues were detected, so i think you can close this issue.

Thanks!
